[2025-10-23T22:53:33.462+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T22:53:33.467+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.run_etl manual__2025-10-23T22:48:16.136349+00:00 [queued]>
[2025-10-23T22:53:33.469+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.run_etl manual__2025-10-23T22:48:16.136349+00:00 [queued]>
[2025-10-23T22:53:33.469+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-10-23T22:53:33.472+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): run_etl> on 2025-10-23 22:48:16.136349+00:00
[2025-10-23T22:53:33.476+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'run_etl', 'manual__2025-10-23T22:48:16.136349+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpbquby8t3']
[2025-10-23T22:53:33.477+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask run_etl
[2025-10-23T22:53:33.477+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=67385) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-23T22:53:33.478+0000] {standard_task_runner.py:72} INFO - Started process 67386 to run task
[2025-10-23T22:53:33.494+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.run_etl manual__2025-10-23T22:48:16.136349+00:00 [running]> on host 596fdc9a152e
[2025-10-23T22:53:33.518+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T22:48:16.136349+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T22:48:16.136349+00:00'
[2025-10-23T22:53:33.518+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-23T22:53:33.519+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-23T22:53:33.519+0000] {logging_mixin.py:190} INFO - Current task name:run_etl state:running start_date:2025-10-23 22:53:33.467728+00:00
[2025-10-23T22:53:33.519+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2025-10-23T22:53:33.519+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-10-23T22:53:33.542+0000] {docker.py:345} INFO - Starting docker container from image etl_image
[2025-10-23T22:53:34.123+0000] {docker.py:69} INFO - 
[2025-10-23T22:53:34.123+0000] {docker.py:69} INFO - === Scraping des entreprises du CAC 40 ===
[2025-10-23T22:53:34.978+0000] {docker.py:69} INFO - 
[2025-10-23T22:53:34.978+0000] {docker.py:69} INFO - Suivi des cours pour 40 entreprises
[2025-10-23T22:53:47.387+0000] {docker.py:69} INFO - /app/transform.py:20: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
[2025-10-23T22:53:47.390+0000] {docker.py:69} INFO -   df = df.replace("N/A", np.nan)
[2025-10-23T22:53:47.391+0000] {docker.py:69} INFO - INFO:load:Tentative de connexion à : postgresql://***:****@postgres:5432/***
[2025-10-23T22:53:47.399+0000] {docker.py:69} INFO - INFO:load:DataFrame à charger : 
[2025-10-23T22:53:47.400+0000] {docker.py:69} INFO -   name   price    change    open                date
[2025-10-23T22:53:47.400+0000] {docker.py:69} INFO - 0   AC   42.21 -0.985226   42.15 2025-10-23 15:36:18
[2025-10-23T22:53:47.400+0000] {docker.py:69} INFO - 1   AI  172.88  0.278429  171.76 2025-10-23 15:39:10
[2025-10-23T22:53:47.401+0000] {docker.py:69} INFO - 2  AIR  207.25  0.704566  206.40 2025-10-23 15:39:11
[2025-10-23T22:53:47.401+0000] {docker.py:69} INFO - 3   MT     NaN       NaN     NaN 2019-06-28 22:07:38
[2025-10-23T22:53:47.401+0000] {docker.py:69} INFO - 4   CS   39.39  0.127095   39.36 2025-10-23 15:39:10
[2025-10-23T22:53:47.429+0000] {docker.py:69} INFO - /app/load.py:55: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-10-23T22:53:47.430+0000] {docker.py:69} INFO -   dataframe.to_sql(
[2025-10-23T22:53:47.431+0000] {docker.py:69} INFO - ERROR:load:Erreur lors du chargement des données : 'Connection' object has no attribute 'cursor'
[2025-10-23T22:53:47.431+0000] {docker.py:69} INFO - ERROR:load:Type d'erreur : AttributeError
[2025-10-23T22:53:47.431+0000] {docker.py:69} INFO - 
[2025-10-23T22:53:47.431+0000] {docker.py:69} INFO - Pipeline ETL terminé avec succès.
[2025-10-23T22:53:47.614+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-10-23T22:53:47.615+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=run_etl, run_id=manual__2025-10-23T22:48:16.136349+00:00, execution_date=20251023T224816, start_date=20251023T225333, end_date=20251023T225347
[2025-10-23T22:53:47.630+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-10-23T22:53:47.631+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-10-23T22:53:47.631+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2025-10-23 22:48:16.140601+00:00
[2025-10-23T22:53:47.631+0000] {logging_mixin.py:190} INFO - Task hostname:596fdc9a152e operator:DockerOperator
[2025-10-23T22:53:47.677+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T22:53:47.685+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-23T22:53:47.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
